# Generated by Django 5.1 on 2026-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_id',
            field=models.CharField(choices=[('clientreq', 'Client Requirements'), ('furniture', 'Furniture Layout'), ('moodboard', 'Mood Board'), ('initial', 'Initial Estimate'), ('design', 'Design'), ('final', 'Final Estimate'), ('pm', 'Project Management'), ('handover', 'Handover'), ('dashboard', 'Dashboard'), ('iam', 'IAM Settings'), ('users', 'User Management')], max_length=30),
        ),
    ]
