# Generated by Django 5.1 on 2026-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pagepermission_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_id',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('projects', 'Projects'), ('clientreq', 'Client Requirements'), ('furniture', 'Furniture Layout'), ('moodboard', 'Mood Board'), ('initial', 'Initial Estimate'), ('booking', 'Booking Form'), ('design', 'Design'), ('final', 'Final Estimate'), ('pm', 'Project Management'), ('handover', 'Handover'), ('tasks', 'Tasks'), ('vendors_material', 'Material Suppliers'), ('vendors_contract', 'Contractors'), ('leads', 'Leads'), ('clients', 'Clients'), ('finance', 'Finance'), ('catalog', 'Furniture Catalogue'), ('items', 'Items Catalogue'), ('library', 'Material Library'), ('users', 'User Management'), ('iam', 'IAM Settings'), ('masters', 'Stage & Site Masters')], max_length=30),
        ),
    ]
