"""
Bundled copy of the base components in the client's supplier price sheet
("sample template.xlsx" → "Sample detail"), generated by
catalog.supplier_specs.parse_workbook so imports work without the file.

Regenerate / refresh from the live workbook instead with:
    python manage.py import_supplier_specs --file "<path to workbook>"
"""
from decimal import Decimal

SUPPLIER_SPECS = [
    {'material': 'Plywood', 'unit': 'sft', 'size': '8x4', 'detail': '12mm Plywood', 'brand': 'Austin', 'model_no': 'Lincoln', 'price': Decimal('95.00'), 'notes': 'Supplier sheet: ₹3,040 per 8x4 sheet (BWP grade)'},
    {'material': 'Plywood', 'unit': 'sft', 'size': '8x4', 'detail': '16mm Plywood', 'brand': 'Austin', 'model_no': 'Lincoln', 'price': Decimal('110.00'), 'notes': 'Supplier sheet: ₹3,520 per 8x4 sheet (BWP grade)'},
    {'material': 'Plywood', 'unit': 'sft', 'size': '8x4', 'detail': '8mm Flexible Plywood', 'brand': 'Austin', 'model_no': 'Lincoln', 'price': Decimal('78.13'), 'notes': 'Supplier sheet: ₹2,500 per 8x4 sheet (BWP grade)'},
    {'material': 'Plywood', 'unit': 'sft', 'size': '8x4', 'detail': '8mm Plywood', 'brand': 'Austin', 'model_no': 'Lincoln', 'price': Decimal('80.00'), 'notes': 'Supplier sheet: ₹2,560 per 8x4 sheet (BWP grade)'},
    {'material': 'Hardware', 'detail': 'Hinge', 'brand': 'Hettich', 'model_no': 'Onsys', 'size': '0 Crank Soft Close', 'price': Decimal('260.00'), 'unit': 'set', 'notes': 'Supplier sheet: per set (hinge + plate)'},
    {'material': 'Hardware', 'detail': 'Hinge', 'brand': 'Hettich', 'model_no': 'Onsys', 'size': '8 Crank Soft Close', 'price': Decimal('260.00'), 'unit': 'set', 'notes': 'Supplier sheet: per set (hinge + plate)'},
    {'material': 'Drawer Channel', 'detail': 'Telescopic channel (pair)', 'brand': 'Hettich', 'model_no': 'Quadro', 'size': '', 'price': Decimal('2600.00'), 'unit': 'set', 'notes': 'Supplier sheet: per set = one pair of slides (one drawer)'},
    {'material': 'Drawer Channel', 'detail': 'Telescopic channel (pair)', 'brand': 'Hettich', 'model_no': 'Quadro', 'size': '18" Soft Close', 'price': Decimal('2600.00'), 'unit': 'set', 'notes': 'Supplier sheet: per set = one pair of slides (one drawer)'},
    {'material': 'Drawer Channel', 'detail': 'Telescopic channel (pair)', 'brand': 'Hettich', 'model_no': 'Quadro', 'size': '12"', 'price': Decimal('2600.00'), 'unit': 'set', 'notes': 'Supplier sheet: per set = one pair of slides (one drawer)'},
    {'material': 'Handle', 'detail': 'Foldable Handles', 'brand': '', 'model_no': 'INR 200 per piece', 'size': '', 'price': Decimal('250.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Gola Profile - C', 'brand': '', 'model_no': '', 'size': '', 'price': Decimal('1500.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Gola Profile - J', 'brand': '', 'model_no': '', 'size': '', 'price': Decimal('1500.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Handle', 'brand': 'Ebco', 'model_no': 'Aluminium Cabinet edge - Silver', 'size': '', 'price': Decimal('1250.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Handle', 'brand': 'Ebco', 'model_no': 'Matt Black - Gola Profile', 'size': '', 'price': Decimal('1250.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Handleless design', 'brand': '', 'model_no': '', 'size': '', 'price': Decimal('550.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Handles', 'brand': '', 'model_no': 'INR 1000 per piece', 'size': '', 'price': Decimal('1200.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Handles', 'brand': '', 'model_no': 'INR 2500 per piece', 'size': '', 'price': Decimal('2500.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Handle', 'detail': 'Knobs', 'brand': '', 'model_no': 'INR 250 per piece', 'size': '', 'price': Decimal('250.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
    {'material': 'Screws', 'detail': 'Nails and screws', 'brand': 'PTA', 'model_no': '', 'size': '', 'price': Decimal('750.00'), 'unit': 'box', 'notes': 'Supplier sheet: per box'},
    {'material': 'Screws', 'detail': 'Nails and screws', 'brand': '', 'model_no': '', 'size': '', 'price': Decimal('750.00'), 'unit': 'box', 'notes': 'Supplier sheet: per box'},
    {'material': 'Edge Band', 'detail': 'PVC edge band', 'brand': 'Shape', 'model_no': 'PVC 22mm x 2mm', 'size': '', 'price': Decimal('60.00'), 'unit': 'm', 'notes': 'Supplier sheet: per metre'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'White', 'size': '8x4', 'price': Decimal('3000.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'Wooden', 'size': '8x4', 'price': Decimal('3000.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'Grey colour', 'size': '8x4', 'price': Decimal('3500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'Off white colour', 'size': '8x4', 'price': Decimal('3500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'Wooden Laminate', 'size': '8x4', 'price': Decimal('3500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Greenlam', 'model_no': 'Grey Wooden Laminate', 'size': '8x4', 'price': Decimal('3500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Laminate', 'detail': '1mm Laminate', 'brand': 'Thermo Laminate', 'model_no': 'Off white', 'size': '8x4', 'price': Decimal('5500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Acrylic', 'detail': 'Acrylic sheet', 'brand': '', 'model_no': 'RM 6104 Fern', 'size': '8x4', 'price': Decimal('4500.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Veneer', 'detail': 'Veneer sheet', 'brand': '', 'model_no': '', 'size': '8x4', 'price': Decimal('6000.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per 8x4 sheet'},
    {'material': 'Adhesive', 'detail': 'Bonding adhesive', 'brand': 'Fevicol', 'model_no': 'Hi - Per', 'size': '', 'price': Decimal('290.00'), 'unit': 'kg', 'notes': 'Supplier sheet: per kg'},
    {'material': 'Adhesive', 'detail': 'Bonding adhesive', 'brand': 'Fevicol', 'model_no': 'Pro Bond', 'size': '', 'price': Decimal('290.00'), 'unit': 'kg', 'notes': 'Supplier sheet: per kg'},
    {'material': 'Polish', 'detail': 'Melamine polish', 'brand': 'Melamine', 'model_no': 'Matt Finish', 'size': '', 'price': Decimal('220.00'), 'unit': 'rft', 'notes': 'Supplier sheet: per rft'},
    {'material': 'Inner Liner', 'detail': 'Inner liner', 'brand': 'Fabric', 'model_no': '0.8mm thick', 'size': '8x4', 'price': Decimal('450.00'), 'unit': 'sheet', 'notes': 'Supplier sheet: per sheet'},
    {'material': 'Drawer Lock', 'detail': 'Drawer lock', 'brand': 'Godrej', 'model_no': 'Nuovo - Draw locks 25mm', 'size': '', 'price': Decimal('650.00'), 'unit': 'nos', 'notes': 'Supplier sheet'},
]
