# Generated by Django 5.1 on 2026-08-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_materialitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('default_unit', models.CharField(default='nos', max_length=20)),
                ('default_length', models.CharField(blank=True, default='', max_length=20)),
                ('default_breadth', models.CharField(blank=True, default='', max_length=20)),
                ('default_height', models.CharField(blank=True, default='', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/furniture/')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_unit', models.CharField(default='nos', help_text='sft, rft, nos, sheets, kg, litre, set, …', max_length=20)),
                ('icon', models.CharField(blank=True, default='🧱', max_length=10)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='🏠', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FurniturePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.furniture')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(help_text='e.g. 18mm Plywood', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('model_no', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.CharField(blank=True, default='', help_text='e.g. 8x4', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='nos', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('library_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_options', to='library.materialitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.material')),
            ],
            options={
                'ordering': ['sort_order', 'brand', 'detail'],
            },
        ),
        migrations.CreateModel(
            name='PartMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_per_unit', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('default_option', models.ForeignKey(blank=True, help_text='Which specific option to price against; defaults to the cheapest active one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_parts', to='catalog.materialoption')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_parts', to='catalog.material')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.furniturepart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='furniture', to='catalog.room'),
        ),
    ]
