# Generated by Django 5.1 on 2026-10-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoption',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('supplier_sheet', 'Supplier sheet')], default='manual', max_length=20),
        ),
    ]
