# Generated by Django 5.1 on 2026-07-16 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0002_alter_materialitem_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Estimate"),
                            ("intermediate", "Intermediate Estimate"),
                            ("final", "Final Estimate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent for Approval"),
                            ("approved", "Approved"),
                            ("revision", "Revision Required"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("material_supplier", "Material Supplier"),
                            ("contractor", "Contractor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("lead_time", models.CharField(blank=True, default="", max_length=50)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.IntegerField()),
                ("area", models.CharField(help_text="Room/area name", max_length=100)),
                ("item", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("length", models.CharField(blank=True, default="", max_length=20)),
                ("breadth", models.CharField(blank=True, default="", max_length=20)),
                ("height", models.CharField(blank=True, default="", max_length=20)),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="unit", max_length=20)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_pct",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.estimate",
                    ),
                ),
            ],
            options={
                "ordering": ["sno"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("client_address", models.TextField(blank=True, default="")),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. Sharma Residence", max_length=200
                    ),
                ),
                (
                    "developer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Developer - Project, e.g. Prestige Lakeside",
                        max_length=200,
                    ),
                ),
                ("unit_no", models.CharField(blank=True, default="", max_length=50)),
                ("city", models.CharField(default="Mumbai", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("pincode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 1,850 sqft",
                        max_length=50,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("1BHK", "1 BHK"),
                            ("2BHK", "2 BHK"),
                            ("3BHK", "3 BHK"),
                            ("4BHK", "4 BHK"),
                            ("Villa", "Villa"),
                            ("Penthouse", "Penthouse"),
                            ("Commercial", "Commercial"),
                            ("Other", "Other"),
                        ],
                        default="3BHK",
                        max_length=20,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                        ],
                        default="Residential",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("Self", "Self"), ("Rental", "Rental")],
                        default="Self",
                        max_length=20,
                    ),
                ),
                (
                    "interior_style",
                    models.CharField(
                        blank=True, default="Contemporary", max_length=100
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("design", "Design"),
                            ("execution", "Execution"),
                            ("completed", "Completed"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="0-100 percentage"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        help_text="Booking Advance, Design Phase P1, etc.",
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NEFT, UPI, RTGS, etc.",
                        max_length=50,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=100)),
                ("plan_verified", models.BooleanField(default=False)),
                ("east", models.CharField(blank=True, default="", max_length=20)),
                ("west", models.CharField(blank=True, default="", max_length=20)),
                ("north", models.CharField(blank=True, default="", max_length=20)),
                ("south", models.CharField(blank=True, default="", max_length=20)),
                ("other_details", models.TextField(blank=True, default="")),
                (
                    "measurement_file",
                    models.FileField(blank=True, upload_to="measurements/%Y/%m/"),
                ),
                (
                    "proof_checked_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("pending", "Pending"),
                            ("issue", "Issue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["room"],
            },
        ),
        migrations.CreateModel(
            name="MaterialSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Plywood, Laminates, Hardware, etc.", max_length=100
                    ),
                ),
                ("room", models.CharField(max_length=100)),
                (
                    "wall_area",
                    models.CharField(help_text="Which wall or area", max_length=100),
                ),
                (
                    "price_range",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "brand_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("catalog", models.CharField(blank=True, default="", max_length=200)),
                ("item_code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "supplier_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("availability", models.CharField(default="In Stock", max_length=50)),
                (
                    "library_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selections",
                        to="library.materialitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_selections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "room"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Floor Protection, False Ceiling, etc.",
                        max_length=200,
                    ),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("delayed", "Delayed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0, help_text="0-100")),
                (
                    "payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_stages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimates",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="DesignRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="Master Bedroom, Kitchen, etc.", max_length=100
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Wardrobe, TV Unit, etc.", max_length=100
                    ),
                ),
                ("length", models.CharField(blank=True, default="", max_length=20)),
                ("breadth", models.CharField(blank=True, default="", max_length=20)),
                ("height", models.CharField(blank=True, default="", max_length=20)),
                ("finishing", models.CharField(blank=True, default="", max_length=100)),
                ("remarks", models.TextField(blank=True, default="")),
                ("design_required", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_requirements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "room", "unit"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("furniture_layout", "Furniture Layout"),
                            ("mood_board", "Mood Board"),
                            ("model_3d", "3D Model"),
                            ("render", "Render"),
                            ("final_render", "Final Render"),
                            ("working_drawing", "Working Drawing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Ver 1, Ver 2, etc.", max_length=20),
                ),
                ("file", models.FileField(blank=True, upload_to="deliverables/%Y/%m/")),
                ("file_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("revision", "Revision Required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["type", "-date"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("check_type", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("inspector", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="estimate",
            unique_together={("project", "type", "version")},
        ),
    ]
