# Generated by Django 5.1 on 2026-06-28 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("project", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(default="Active", max_length=50)),
                ("budget", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_no", models.IntegerField()),
                (
                    "area",
                    models.CharField(
                        help_text="Kitchen, Living, Suite 1, etc.", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Furniture, Electrical, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "item",
                    models.CharField(
                        help_text="Wardrobe, TV Console, etc.", max_length=200
                    ),
                ),
                ("finish", models.CharField(blank=True, default="", max_length=200)),
                ("width_ft", models.IntegerField(default=0)),
                ("width_in", models.IntegerField(default=0)),
                ("height_ft", models.IntegerField(default=0)),
                ("height_in", models.IntegerField(default=0)),
                ("depth_ft", models.IntegerField(default=0)),
                ("depth_in", models.IntegerField(default=0)),
                (
                    "vendor_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Service Vendor / Product Vendor",
                        max_length=50,
                    ),
                ),
                (
                    "fac_or_site",
                    models.CharField(
                        blank=True,
                        choices=[("Factory", "Factory"), ("Site", "Site")],
                        default="Factory",
                        max_length=20,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(blank=True, default="Sft", max_length=20)),
                (
                    "budget_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["si_no"],
            },
        ),
        migrations.CreateModel(
            name="MoodBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("lead_time", models.CharField(blank=True, default="", max_length=50)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("projects_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EstimateItemSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Procurement", "Procurement"),
                            ("Service", "Service"),
                            ("Spec Purpose", "Spec Purpose"),
                            ("Procurement cum Service", "Procurement cum Service"),
                        ],
                        default="Procurement",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. Core Material(16mm BWP Ply)", max_length=100
                    ),
                ),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                (
                    "specification",
                    models.CharField(help_text="Full display text", max_length=500),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=20)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="qty × rate",
                        max_digits=12,
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(decimal_places=2, default=35, max_digits=5),
                ),
                (
                    "margin_amt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_pct",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                (
                    "gst_amt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="cost + margin + gst",
                        max_digits=12,
                    ),
                ),
                (
                    "service_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimate_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="projects.estimateitem",
                    ),
                ),
                (
                    "library_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_specs",
                        to="library.materialitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MoodBoardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="moodboards/%Y/%m/")),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "mood_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.moodboard",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. Sharma Residence", max_length=200
                    ),
                ),
                ("developer", models.CharField(blank=True, default="", max_length=200)),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Society/building name, e.g. ABC Homes",
                        max_length=200,
                    ),
                ),
                ("unit_no", models.CharField(blank=True, default="", max_length=50)),
                ("city", models.CharField(default="Mumbai", max_length=100)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Area/locality, e.g. Bandra",
                        max_length=200,
                    ),
                ),
                (
                    "super_built_up_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "carpet_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("1BHK", "1 BHK"),
                            ("2BHK", "2 BHK"),
                            ("3BHK", "3 BHK"),
                            ("4BHK", "4 BHK"),
                            ("Villa", "Villa"),
                            ("Penthouse", "Penthouse"),
                            ("Commercial", "Commercial"),
                            ("Other", "Other"),
                        ],
                        default="3BHK",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("purpose", models.CharField(default="Primary Home", max_length=50)),
                ("use", models.CharField(default="Self Use", max_length=50)),
                (
                    "interior_style",
                    models.CharField(
                        blank=True, default="Contemporary", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Client Requirements", "Client Requirements"),
                            ("Furniture Layout", "Furniture Layout"),
                            ("Mood Board", "Mood Board"),
                            ("Initial Estimate", "Initial Estimate"),
                            ("Design", "Design"),
                            ("Final Estimate", "Final Estimate"),
                            ("Execution", "Execution"),
                            ("Handover", "Handover"),
                        ],
                        default="Initial Estimate",
                        max_length=30,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="0-100 percentage"),
                ),
                ("handover_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(help_text="P1, P2, P3, etc.", max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode",
                    models.CharField(
                        choices=[("Bank", "Bank Transfer"), ("Cash", "Cash")],
                        default="Bank",
                        max_length=10,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["stage"],
            },
        ),
        migrations.AddField(
            model_name="moodboard",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moodboards",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="FurnitureLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("file", models.FileField(upload_to="layouts/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="estimateitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimate_items",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("selected", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="estimateitem",
            unique_together={("project", "si_no")},
        ),
    ]
