# Generated by Django 5.1 on 2026-08-03 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Agreed project value at booking time', max_digits=14)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_received', models.BooleanField(default=False)),
                ('advance_received_on', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Card', 'Card')], default='', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('payment_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('signed_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_file', models.FileField(blank=True, upload_to='bookings/signatures/%Y/%m/')),
                ('generated_pdf', models.FileField(blank=True, upload_to='bookings/pdf/%Y/%m/')),
                ('scope_summary', models.TextField(blank=True, default='', help_text='Short description of what is being booked')),
                ('terms', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['sno', 'id']},
        ),
        migrations.AddField(
            model_name='estimate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, help_text='Master item this line was created from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='items.item'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed as qty × rate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='sno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='projects.estimate'),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_form', to='projects.project'),
        ),
    ]
