# Generated by Django 5.1 on 2026-08-03 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_bookingform_delete_vendor_alter_estimateitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
