# Generated by Django 5.1 on 2026-08-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_bookingform_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='property_type',
            field=models.CharField(choices=[('1BHK Apartment', '1 BHK Apartment'), ('2BHK Apartment', '2 BHK Apartment'), ('3BHK Apartment', '3BHK Apartment'), ('4BHK Apartment', '4BHK Apartment'), ('Independent Villa', 'Independent Villa'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Row House', 'Row House'), ('Commercial Office', 'Commercial Office'), ('Commercial Retail', 'Commercial Retail'), ('Other', 'Other')], default='3BHK Apartment', max_length=20),
        ),
    ]
