# Generated by Django 5.1 on 2026-08-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('projects', '0004_alter_project_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeliverable',
            options={'ordering': ['type', '-version_no', '-date']},
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.client'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Bytes'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='is_current',
            field=models.BooleanField(default=True, help_text='The live version for this type — the one shown to the client.'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='deliverables/preview/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='review_remarks',
            field=models.TextField(blank=True, default='', help_text='Why it was approved or sent back'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='projects.projectdeliverable'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='deliverables/thumbs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectdeliverable',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Sent for Approval'), ('approved', 'Approved'), ('revision', 'Revision Required')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectdeliverable',
            index=models.Index(fields=['project', 'type', 'is_current'], name='projects_pr_project_0acb28_idx'),
        ),
    ]
