# Generated by Django 5.1 on 2026-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_backfill_deliverable_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliverable',
            name='version',
            field=models.CharField(blank=True, help_text='Ver 1, Ver 2, etc.', max_length=20),
        ),
    ]
