# Generated by Django 5.1 on 2026-08-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('projects', '0007_alter_projectdeliverable_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='finishing',
            field=models.CharField(blank=True, default='', help_text='e.g. Laminate, Veneer', max_length=100),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='zone',
            field=models.CharField(blank=True, default='', help_text='Room area, e.g. East Wall', max_length=100),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of the component breakdown when present, else qty × rate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='area',
            field=models.CharField(help_text='Room name, e.g. Master Bedroom', max_length=100),
        ),
        migrations.CreateModel(
            name='EstimateItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('basic_component', models.CharField(help_text='e.g. Plywood, Laminate, Hinges', max_length=150)),
                ('detail', models.CharField(blank=True, default='', help_text='e.g. 18mm', max_length=150)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed as qty × price', max_digits=12)),
                ('catalog_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.material')),
                ('catalog_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.materialoption')),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.estimateitem')),
            ],
            options={
                'ordering': ['sno', 'id'],
            },
        ),
    ]
