# Generated by Django 5.1 on 2026-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_estimateitem_category_estimateitem_finishing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Room name, e.g. Master Bedroom', max_length=100),
        ),
    ]
