# Generated by Django 5.1 on 2026-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_estimateitem_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
