# Generated by Django 5.1 on 2026-08-03 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_materialitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, default='📦', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Auto-generated, e.g. CARP-WARDROBE', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Default spec text copied onto estimate lines')),
                ('default_room', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(choices=[('unit', 'Unit'), ('nos', 'Nos'), ('sft', 'Sq. Ft.'), ('rft', 'Running Ft.'), ('sqm', 'Sq. Metre'), ('set', 'Set'), ('lot', 'Lot'), ('lumpsum', 'Lump Sum')], default='unit', max_length=20)),
                ('calc_method', models.CharField(choices=[('per_unit', 'Per Unit (qty × rate)'), ('area_lb', 'Area — Length × Breadth'), ('area_lh', 'Area — Length × Height'), ('running_length', 'Running Length'), ('lumpsum', 'Lump Sum')], default='per_unit', max_length=20)),
                ('default_length', models.CharField(blank=True, default='', max_length=20)),
                ('default_breadth', models.CharField(blank=True, default='', max_length=20)),
                ('default_height', models.CharField(blank=True, default='', max_length=20)),
                ('default_qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.itemcategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('material', 'Material'), ('service', 'Service / Labour')], default='material', max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text='Free-text name when no library record is linked', max_length=200)),
                ('qty_per_unit', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit', models.CharField(default='nos', max_length=20)),
                ('rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the linked library rate', max_digits=12, null=True)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='items.item')),
                ('material_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_items', to='library.materialitem')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_items', to='library.serviceitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='items_item_categor_43a476_idx'),
        ),
    ]
