# Generated by Django 5.1 on 2026-08-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='catalog_furniture',
            field=models.ForeignKey(blank=True, help_text='Furniture catalogue entry whose bill-of-materials backs this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='catalog.furniture'),
        ),
    ]
