# Generated by Django 5.1 on 2026-08-03 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_alter_materialitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Auto-generated short code, e.g. SUP-RAJTIM or CON-SHREEF', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('material_supplier', 'Material Supplier'), ('contractor', 'Contractor')], db_index=True, max_length=20)),
                ('legal_name', models.CharField(blank=True, default='', help_text='Registered business name, if different', max_length=250)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('gst_number', models.CharField(blank=True, default='', help_text='15-character GSTIN', max_length=15)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=15)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_terms', models.CharField(choices=[('advance', '100% Advance'), ('part_advance', 'Part Advance'), ('on_delivery', 'On Delivery'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('milestone', 'Milestone Based')], default='on_delivery', max_length=20)),
                ('credit_days', models.IntegerField(default=0)),
                ('advance_pct', models.DecimalField(decimal_places=2, default=0, help_text='Advance percentage typically demanded', max_digits=5)),
                ('brands_supplied', models.CharField(blank=True, default='', help_text='Comma-separated brand names, e.g. Austin, Greenlam, Hettich', max_length=500)),
                ('lead_time_days', models.IntegerField(default=0, help_text='Typical delivery lead time in days')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivers_on_site', models.BooleanField(default=True)),
                ('trade', models.CharField(blank=True, choices=[('carpentry', 'Carpentry'), ('false_ceiling', 'False Ceiling'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('flooring', 'Flooring & Tiling'), ('glass', 'Glass & Mirror'), ('civil', 'Civil & Masonry'), ('fabrication', 'Metal Fabrication'), ('hvac', 'HVAC'), ('upholstery', 'Upholstery'), ('cleaning', 'Cleaning & Housekeeping'), ('other', 'Other')], default='', max_length=30)),
                ('specialization', models.CharField(blank=True, default='', max_length=300)),
                ('team_size', models.IntegerField(default=0)),
                ('labour_rate_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='0.0 – 5.0', max_digits=3)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
                ('material_categories', models.ManyToManyField(blank=True, help_text='Which library categories this supplier stocks', related_name='suppliers', to='library.materialcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('gst', 'GST Certificate'), ('pan', 'PAN Card'), ('cheque', 'Cancelled Cheque'), ('agreement', 'Agreement / MoU'), ('rate_card', 'Rate Card'), ('catalogue', 'Catalogue'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='vendors/documents/%Y/%m/')),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_type', 'is_active'], name='vendors_ven_vendor__20d7ff_idx'),
        ),
    ]
